function Options = initialiseOptionsStruct()

Options = struct('acceptanceFcn',[],'generatorFcn',[],'coolingFcn',[],...
    'initialTemperature',[],'coolingFactor',[],'maxIterations',[],...
    'maxIterPerTemp',[],'maxAccept',[],'maxConsReject',[],...
    'minTemperature',[],'display',[],'plot',[]);
